# Generated by Django 3.1 on 2020-08-14 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benford', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='significantdigit',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='significant_digits', to='benford.dataset'),
        ),
        migrations.AlterUniqueTogether(
            name='significantdigit',
            unique_together={('dataset', 'digit')},
        ),
    ]
