# Generated by Django 3.1 on 2020-08-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benford', '0003_dataset_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='significantdigit',
            name='percentage',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
