# Generated by Django 3.1 on 2020-08-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benford', '0004_significantdigit_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='significantdigit',
            name='occurences',
            field=models.PositiveIntegerField(),
        ),
    ]
