# Generated by Django 3.1 on 2020-08-15 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benford', '0007_dataset_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='significantdigit',
            name='percentage',
        ),
    ]
