# Generated by Django 3.1 on 2020-08-17 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benford', '0008_remove_significantdigit_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.PositiveIntegerField(db_index=True, verbose_name='line number')),
                ('data', models.JSONField(default=list)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='benford.dataset')),
            ],
            options={
                'unique_together': {('dataset', 'line')},
            },
        ),
    ]
