# Generated by Django 3.1 on 2020-08-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benford', '0009_datasetrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetrow',
            name='has_error',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterIndexTogether(
            name='datasetrow',
            index_together={('dataset', 'has_error')},
        ),
    ]
